#!/usr/bin/env bash
# MySQL replica configuration file

[mysqld]
# Configure replication settings
server-id = 2
relay-log = /var/log/mysql/mysql-relay-bin.log
log_bin = /var/log/mysql/mysql-bin.log
binlog_do_db = tyrell_corp
master-host = web-01
master-user = replica_user
master-password = your_replica_user_password
master-connect-retry = 60
replicate-do-db = tyrell_corp

# Other MySQL configurations...

