#!/usr/bin/env bash
#terminate indefinate loop
if pgrep "4-to_infinity_and_beyond" > /dev/null; then
	pid=$(pgrep "4-to_infinity_and_beyond")
	kill "$pid"
	echo "Terminated"
else
	echo "Process is not running"
fi
