#!/bin/bash

#default policy to block all incoming traffic
sudo ufw default deny incoming
#default policy to block all outgoing traffic
sudo ufw default allow outgoing

#allowed ports
sudo ufw allow 22/tcp #ssh
sudo ufw allow 443/tcp #https ssl
sudo ufw allow 80/tcp #HTTP

#enable UFW
sudo ufw --force enable
